# Generated by Django 2.2.5 on 2021-01-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210109_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('Github', 'Github'), ('Kakao', 'Kakao')], default='email', max_length=50),
        ),
    ]
